import type { SourceAdapter, SourceAdapterConfig } from "@/lib/sources/types";
import type { NormalizedListing } from "@/types/listing";

// Deterministic sample data so the MVP is fully demoable without any paid
// API keys or live scraping. Swap for real adapters as licensed access is
// obtained (see docs/LEGAL_AND_DATA_SOURCES.md).
export async function mockListings(): Promise<NormalizedListing[]> {
  const now = new Date().toISOString();
  const base: Omit<NormalizedListing, "externalId" | "title">[] = [];
  void base;

  const raw: Array<Partial<NormalizedListing> & Pick<NormalizedListing, "externalId" | "title" | "monthlyRentCents" | "bedrooms" | "category" | "city" | "state" | "zipCode" | "listingUrl">> = [
    {
      externalId: "mock-001",
      title: "Sunny Studio Near Downtown",
      city: "Columbus",
      state: "OH",
      zipCode: "43215",
      latitude: 39.9622,
      longitude: -83.0007,
      monthlyRentCents: 89500,
      securityDepositCents: 89500,
      bedrooms: 0,
      bathrooms: 1,
      squareFeet: 480,
      category: "STUDIO",
      utilitiesIncluded: true,
      petFriendly: false,
      parkingAvailable: true,
      furnished: false,
      listingUrl: "https://example.invalid/listings/mock-001",
      contactName: "Riverfront Property Group",
      contactPhone: "+16145550101",
      contactEmail: "leasing@riverfront.invalid",
      sourceType: "PROPERTY_MANAGER_SITE",
    },
    {
      externalId: "mock-002",
      title: "Affordable 1BR - Income Restricted",
      city: "Columbus",
      state: "OH",
      zipCode: "43206",
      latitude: 39.9445,
      longitude: -82.9865,
      monthlyRentCents: 71000,
      securityDepositCents: 35000,
      bedrooms: 1,
      bathrooms: 1,
      squareFeet: 620,
      category: "ONE_BEDROOM",
      lowDeposit: true,
      listingUrl: "https://example.invalid/affordable/mock-002",
      contactName: "South Side Housing Authority",
      contactPhone: "+16145550102",
      contactEmail: "info@southsideha.invalid",
      sourceType: "AFFORDABLE_HOUSING",
    },
    {
      externalId: "mock-003",
      title: "Private Room in Shared 3BR House",
      city: "Columbus",
      state: "OH",
      zipCode: "43201",
      latitude: 39.9989,
      longitude: -83.0126,
      monthlyRentCents: 55000,
      securityDepositCents: 55000,
      bedrooms: 0,
      bathrooms: 1.5,
      category: "PRIVATE_ROOM",
      furnished: true,
      shortTermLease: true,
      listingUrl: "https://example.invalid/rooms/mock-003",
      contactName: "Jordan T.",
      contactPhone: "+16145550103",
      sourceType: "ROOM_RENTAL_PLATFORM",
    },
    {
      externalId: "mock-004",
      title: "Modern 2BR Near Transit",
      city: "Columbus",
      state: "OH",
      zipCode: "43210",
      latitude: 40.0067,
      longitude: -83.0305,
      monthlyRentCents: 145000,
      securityDepositCents: 145000,
      applicationFeeCents: 5000,
      bedrooms: 2,
      bathrooms: 2,
      squareFeet: 980,
      category: "TWO_BEDROOM",
      petFriendly: true,
      parkingAvailable: true,
      listingUrl: "https://example.invalid/listings/mock-004",
      contactName: "Campus Realty",
      contactPhone: "+16145550104",
      contactEmail: "hello@campusrealty.invalid",
      officeHours: "Mon-Fri 9am-6pm, Sat 10am-2pm",
      sourceType: "MAJOR_MARKETPLACE",
    },
    {
      externalId: "mock-005",
      title: "House Share - 4 Bedrooms Available Individually",
      city: "Columbus",
      state: "OH",
      zipCode: "43202",
      latitude: 40.0234,
      longitude: -83.0089,
      monthlyRentCents: 62000,
      securityDepositCents: 30000,
      bedrooms: 1,
      bathrooms: 1,
      category: "HOUSE_SHARE",
      furnished: true,
      noCreditCheck: true,
      listingUrl: "https://example.invalid/classifieds/mock-005",
      contactPhone: "+16145550105",
      sourceType: "CLASSIFIED",
    },
    {
      externalId: "mock-006",
      title: "Studio - TOO GOOD TO BE TRUE $200/mo wire deposit today",
      city: "Columbus",
      state: "OH",
      zipCode: "43215",
      monthlyRentCents: 20000,
      bedrooms: 0,
      category: "STUDIO",
      listingUrl: "https://example.invalid/classifieds/mock-006",
      contactEmail: "wiretransfer@scam-example.invalid",
      description: "Owner overseas, send deposit via wire transfer or gift card before viewing.",
      sourceType: "CLASSIFIED",
    },
    {
      externalId: "mock-007",
      title: "Senior Housing 1BR - Workforce Program",
      city: "Columbus",
      state: "OH",
      zipCode: "43223",
      latitude: 39.9312,
      longitude: -83.0512,
      monthlyRentCents: 68000,
      securityDepositCents: 20000,
      bedrooms: 1,
      bathrooms: 1,
      squareFeet: 560,
      category: "ONE_BEDROOM",
      lowDeposit: true,
      listingUrl: "https://example.invalid/affordable/mock-007",
      contactName: "West Columbus Senior Communities",
      contactPhone: "+16145550107",
      contactEmail: "leasing@wcsc.invalid",
      sourceType: "AFFORDABLE_HOUSING",
    },
    {
      externalId: "mock-008",
      title: "Compact Studio Near Downtown LA",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90012",
      latitude: 34.0522,
      longitude: -118.2437,
      monthlyRentCents: 165000,
      securityDepositCents: 165000,
      bedrooms: 0,
      bathrooms: 1,
      squareFeet: 420,
      category: "STUDIO",
      parkingAvailable: false,
      listingUrl: "https://example.invalid/listings/mock-008",
      contactName: "Angeleno Property Partners",
      contactPhone: "+13235550108",
      contactEmail: "leasing@angeleno.invalid",
      sourceType: "PROPERTY_MANAGER_SITE",
    },
    {
      externalId: "mock-009",
      title: "1BR Near Balboa Park",
      city: "San Diego",
      state: "CA",
      zipCode: "92103",
      latitude: 32.7157,
      longitude: -117.1611,
      monthlyRentCents: 210000,
      securityDepositCents: 100000,
      applicationFeeCents: 4500,
      bedrooms: 1,
      bathrooms: 1,
      squareFeet: 650,
      category: "ONE_BEDROOM",
      petFriendly: true,
      parkingAvailable: true,
      listingUrl: "https://example.invalid/listings/mock-009",
      contactName: "Balboa Rentals",
      contactPhone: "+16195550109",
      contactEmail: "hello@balboarentals.invalid",
      officeHours: "Mon-Fri 9am-5pm",
      sourceType: "MAJOR_MARKETPLACE",
    },
    {
      externalId: "mock-010",
      title: "Private Room in Shared Flat, SF",
      city: "San Francisco",
      state: "CA",
      zipCode: "94110",
      latitude: 37.7749,
      longitude: -122.4194,
      monthlyRentCents: 145000,
      securityDepositCents: 145000,
      bedrooms: 0,
      bathrooms: 1,
      category: "PRIVATE_ROOM",
      furnished: true,
      shortTermLease: true,
      listingUrl: "https://example.invalid/rooms/mock-010",
      contactName: "Mission Room Co-op",
      contactPhone: "+14155550110",
      sourceType: "ROOM_RENTAL_PLATFORM",
    },
    {
      externalId: "mock-011",
      title: "Affordable 1BR - Income Restricted, Phoenix",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85006",
      latitude: 33.4484,
      longitude: -112.0740,
      monthlyRentCents: 89000,
      securityDepositCents: 40000,
      bedrooms: 1,
      bathrooms: 1,
      squareFeet: 610,
      category: "ONE_BEDROOM",
      lowDeposit: true,
      listingUrl: "https://example.invalid/affordable/mock-011",
      contactName: "Valley Housing Alliance",
      contactPhone: "+16025550111",
      contactEmail: "info@valleyha.invalid",
      sourceType: "AFFORDABLE_HOUSING",
    },
    {
      externalId: "mock-012",
      title: "House Share - Room Available, Central Phoenix",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85015",
      latitude: 33.4942,
      longitude: -112.0929,
      monthlyRentCents: 68000,
      securityDepositCents: 30000,
      bedrooms: 1,
      bathrooms: 1,
      category: "HOUSE_SHARE",
      furnished: true,
      noCreditCheck: true,
      listingUrl: "https://example.invalid/classifieds/mock-012",
      contactPhone: "+16025550112",
      sourceType: "CLASSIFIED",
    },
    {
      externalId: "mock-013",
      title: "Cozy Studio Near U of A",
      city: "Tucson",
      state: "AZ",
      zipCode: "85719",
      latitude: 32.2226,
      longitude: -110.9747,
      monthlyRentCents: 79500,
      securityDepositCents: 79500,
      bedrooms: 0,
      bathrooms: 1,
      squareFeet: 400,
      category: "STUDIO",
      furnished: false,
      listingUrl: "https://example.invalid/listings/mock-013",
      contactName: "Old Pueblo Leasing",
      contactPhone: "+15205550113",
      contactEmail: "leasing@oldpueblo.invalid",
      sourceType: "UNIVERSITY_HOUSING",
    },
    {
      externalId: "mock-014",
      title: "1BR Walkable to Downtown Austin",
      city: "Austin",
      state: "TX",
      zipCode: "78701",
      latitude: 30.2672,
      longitude: -97.7431,
      monthlyRentCents: 195000,
      securityDepositCents: 100000,
      applicationFeeCents: 5000,
      bedrooms: 1,
      bathrooms: 1,
      squareFeet: 700,
      category: "ONE_BEDROOM",
      petFriendly: true,
      parkingAvailable: true,
      furnished: false,
      listingUrl: "https://example.invalid/listings/mock-014",
      contactName: "Capitol City Realty",
      contactPhone: "+15125550114",
      contactEmail: "hello@capitolcityrealty.invalid",
      officeHours: "Mon-Sat 9am-6pm",
      sourceType: "MAJOR_MARKETPLACE",
    },
    {
      externalId: "mock-015",
      title: "Modern 2BR Near Med Center, Houston",
      city: "Houston",
      state: "TX",
      zipCode: "77030",
      latitude: 29.7604,
      longitude: -95.3698,
      monthlyRentCents: 155000,
      securityDepositCents: 155000,
      bedrooms: 2,
      bathrooms: 2,
      squareFeet: 950,
      category: "TWO_BEDROOM",
      petFriendly: true,
      parkingAvailable: true,
      utilitiesIncluded: true,
      listingUrl: "https://example.invalid/listings/mock-015",
      contactName: "Bayou City Properties",
      contactPhone: "+17135550115",
      contactEmail: "leasing@bayoucity.invalid",
      sourceType: "PROPERTY_MANAGER_SITE",
    },
    {
      externalId: "mock-016",
      title: "Senior Housing Studio - Workforce Program, Dallas",
      city: "Dallas",
      state: "TX",
      zipCode: "75201",
      latitude: 32.7767,
      longitude: -96.7970,
      monthlyRentCents: 72000,
      securityDepositCents: 25000,
      bedrooms: 0,
      bathrooms: 1,
      squareFeet: 480,
      category: "STUDIO",
      lowDeposit: true,
      listingUrl: "https://example.invalid/affordable/mock-016",
      contactName: "Big D Senior Communities",
      contactPhone: "+12145550116",
      contactEmail: "leasing@bigdseniors.invalid",
      sourceType: "AFFORDABLE_HOUSING",
    },
    {
      externalId: "mock-017",
      title: "Roommate Wanted - 3BR House, Dallas",
      city: "Dallas",
      state: "TX",
      zipCode: "75204",
      latitude: 32.8024,
      longitude: -96.7847,
      monthlyRentCents: 82000,
      securityDepositCents: 40000,
      bedrooms: 1,
      bathrooms: 1,
      category: "ROOMMATE",
      furnished: true,
      shortTermLease: true,
      listingUrl: "https://example.invalid/rooms/mock-017",
      contactName: "Casey M.",
      contactPhone: "+12145550117",
      sourceType: "ROOM_RENTAL_PLATFORM",
    },
  ];

  return raw.map((r) => ({
    externalId: r.externalId,
    sourceName: "rentradar-mock",
    sourceType: r.sourceType ?? "MANUAL",
    title: r.title,
    description: r.description,
    addressLine1: r.addressLine1,
    city: r.city,
    state: r.state,
    zipCode: r.zipCode,
    latitude: r.latitude,
    longitude: r.longitude,
    monthlyRentCents: r.monthlyRentCents,
    securityDepositCents: r.securityDepositCents,
    applicationFeeCents: r.applicationFeeCents,
    otherMoveInFeesCents: r.otherMoveInFeesCents,
    utilitiesIncluded: r.utilitiesIncluded,
    bedrooms: r.bedrooms,
    bathrooms: r.bathrooms,
    squareFeet: r.squareFeet,
    category: r.category,
    petFriendly: r.petFriendly,
    parkingAvailable: r.parkingAvailable,
    furnished: r.furnished,
    shortTermLease: r.shortTermLease,
    noCreditCheck: r.noCreditCheck,
    lowDeposit: r.lowDeposit,
    listingUrl: r.listingUrl,
    contactName: r.contactName,
    contactPhone: r.contactPhone,
    contactEmail: r.contactEmail,
    contactFormUrl: r.contactFormUrl,
    officeHours: r.officeHours,
    foundAt: now,
  }));
}

export const mockAdapter: SourceAdapter = {
  meta: {
    name: "rentradar-mock",
    legallyIntegrated: true,
    requiresApiKey: false,
    notes: "Static sample data for local development, demos, and tests.",
  },
  async fetchListings(_config: SourceAdapterConfig) {
    return mockListings();
  },
};
