import type { SourceAdapter, SourceAdapterConfig } from "@/lib/sources/types";
import type { NormalizedListing } from "@/types/listing";

// Deterministic sample data so the MVP is fully demoable without any paid
// API keys or live scraping. Swap for real adapters as licensed access is
// obtained (see docs/LEGAL_AND_DATA_SOURCES.md).
export async function mockListings(): Promise<NormalizedListing[]> {
  const now = new Date().toISOString();
  const base: Omit<NormalizedListing, "externalId" | "title">[] = [];
  void base;

  const raw: Array<Partial<NormalizedListing> & Pick<NormalizedListing, "externalId" | "title" | "monthlyRentCents" | "bedrooms" | "category" | "city" | "state" | "zipCode" | "listingUrl">> = [
    {
      externalId: "mock-001",
      title: "Sunny Studio Near Downtown",
      city: "Columbus",
      state: "OH",
      zipCode: "43215",
      latitude: 39.9622,
      longitude: -83.0007,
      monthlyRentCents: 89500,
      securityDepositCents: 89500,
      bedrooms: 0,
      bathrooms: 1,
      squareFeet: 480,
      category: "STUDIO",
      utilitiesIncluded: true,
      petFriendly: false,
      parkingAvailable: true,
      furnished: false,
      listingUrl: "https://example.invalid/listings/mock-001",
      contactName: "Riverfront Property Group",
      contactPhone: "+16145550101",
      contactEmail: "leasing@riverfront.invalid",
      sourceType: "PROPERTY_MANAGER_SITE",
    },
    {
      externalId: "mock-002",
      title: "Affordable 1BR - Income Restricted",
      city: "Columbus",
      state: "OH",
      zipCode: "43206",
      latitude: 39.9445,
      longitude: -82.9865,
      monthlyRentCents: 71000,
      securityDepositCents: 35000,
      bedrooms: 1,
      bathrooms: 1,
      squareFeet: 620,
      category: "ONE_BEDROOM",
      lowDeposit: true,
      listingUrl: "https://example.invalid/affordable/mock-002",
      contactName: "South Side Housing Authority",
      contactPhone: "+16145550102",
      contactEmail: "info@southsideha.invalid",
      sourceType: "AFFORDABLE_HOUSING",
    },
    {
      externalId: "mock-003",
      title: "Private Room in Shared 3BR House",
      city: "Columbus",
      state: "OH",
      zipCode: "43201",
      latitude: 39.9989,
      longitude: -83.0126,
      monthlyRentCents: 55000,
      securityDepositCents: 55000,
      bedrooms: 0,
      bathrooms: 1.5,
      category: "PRIVATE_ROOM",
      furnished: true,
      shortTermLease: true,
      listingUrl: "https://example.invalid/rooms/mock-003",
      contactName: "Jordan T.",
      contactPhone: "+16145550103",
      sourceType: "ROOM_RENTAL_PLATFORM",
    },
    {
      externalId: "mock-004",
      title: "Modern 2BR Near Transit",
      city: "Columbus",
      state: "OH",
      zipCode: "43210",
      latitude: 40.0067,
      longitude: -83.0305,
      monthlyRentCents: 145000,
      securityDepositCents: 145000,
      applicationFeeCents: 5000,
      bedrooms: 2,
      bathrooms: 2,
      squareFeet: 980,
      category: "TWO_BEDROOM",
      petFriendly: true,
      parkingAvailable: true,
      listingUrl: "https://example.invalid/listings/mock-004",
      contactName: "Campus Realty",
      contactPhone: "+16145550104",
      contactEmail: "hello@campusrealty.invalid",
      officeHours: "Mon-Fri 9am-6pm, Sat 10am-2pm",
      sourceType: "MAJOR_MARKETPLACE",
    },
    {
      externalId: "mock-005",
      title: "House Share - 4 Bedrooms Available Individually",
      city: "Columbus",
      state: "OH",
      zipCode: "43202",
      latitude: 40.0234,
      longitude: -83.0089,
      monthlyRentCents: 62000,
      securityDepositCents: 30000,
      bedrooms: 1,
      bathrooms: 1,
      category: "HOUSE_SHARE",
      furnished: true,
      noCreditCheck: true,
      listingUrl: "https://example.invalid/classifieds/mock-005",
      contactPhone: "+16145550105",
      sourceType: "CLASSIFIED",
    },
    {
      externalId: "mock-006",
      title: "Studio - TOO GOOD TO BE TRUE $200/mo wire deposit today",
      city: "Columbus",
      state: "OH",
      zipCode: "43215",
      monthlyRentCents: 20000,
      bedrooms: 0,
      category: "STUDIO",
      listingUrl: "https://example.invalid/classifieds/mock-006",
      contactEmail: "wiretransfer@scam-example.invalid",
      description: "Owner overseas, send deposit via wire transfer or gift card before viewing.",
      sourceType: "CLASSIFIED",
    },
    {
      externalId: "mock-007",
      title: "Senior Housing 1BR - Workforce Program",
      city: "Columbus",
      state: "OH",
      zipCode: "43223",
      latitude: 39.9312,
      longitude: -83.0512,
      monthlyRentCents: 68000,
      securityDepositCents: 20000,
      bedrooms: 1,
      bathrooms: 1,
      squareFeet: 560,
      category: "ONE_BEDROOM",
      lowDeposit: true,
      listingUrl: "https://example.invalid/affordable/mock-007",
      contactName: "West Columbus Senior Communities",
      contactPhone: "+16145550107",
      contactEmail: "leasing@wcsc.invalid",
      sourceType: "AFFORDABLE_HOUSING",
    },
  ];

  return raw.map((r) => ({
    externalId: r.externalId,
    sourceName: "rentradar-mock",
    sourceType: r.sourceType ?? "MANUAL",
    title: r.title,
    description: r.description,
    addressLine1: r.addressLine1,
    city: r.city,
    state: r.state,
    zipCode: r.zipCode,
    latitude: r.latitude,
    longitude: r.longitude,
    monthlyRentCents: r.monthlyRentCents,
    securityDepositCents: r.securityDepositCents,
    applicationFeeCents: r.applicationFeeCents,
    otherMoveInFeesCents: r.otherMoveInFeesCents,
    utilitiesIncluded: r.utilitiesIncluded,
    bedrooms: r.bedrooms,
    bathrooms: r.bathrooms,
    squareFeet: r.squareFeet,
    category: r.category,
    petFriendly: r.petFriendly,
    parkingAvailable: r.parkingAvailable,
    furnished: r.furnished,
    shortTermLease: r.shortTermLease,
    noCreditCheck: r.noCreditCheck,
    lowDeposit: r.lowDeposit,
    listingUrl: r.listingUrl,
    contactName: r.contactName,
    contactPhone: r.contactPhone,
    contactEmail: r.contactEmail,
    contactFormUrl: r.contactFormUrl,
    officeHours: r.officeHours,
    foundAt: now,
  }));
}

export const mockAdapter: SourceAdapter = {
  meta: {
    name: "rentradar-mock",
    legallyIntegrated: true,
    requiresApiKey: false,
    notes: "Static sample data for local development, demos, and tests.",
  },
  async fetchListings(_config: SourceAdapterConfig) {
    return mockListings();
  },
};
